'use client';
import { useEffect, useState } from 'react';
import { services } from '../data/services';
import { gallery, type GalleryItem } from '../data/gallery';
import { instagramDisplayMode, instagramPosts } from '../data/instagram';
import { reviews } from '../data/reviews';
import { aboutContent } from '../data/content';

interface InstallPromptEvent extends Event { prompt: () => Promise<void>; userChoice: Promise<{ outcome: 'accepted' | 'dismissed' }> }

const IG='https://instagram.com/_semi_kang';
const THREADS='https://www.threads.com/@_semi_kang';
const MAP='https://map.kakao.com/link/search/대구광역시 북구 경진로1길 51-1';
const NAVER='https://map.naver.com/p/search/보미뷰티 대구 복현동';
const instagramEmbed=(url:string)=>`${url.replace(/\?.*$/,'').replace(/\/$/,'')}/embed/`;

export default function Home(){
 const [menu,setMenu]=useState(false); const [filter,setFilter]=useState('ALL'); const [selected,setSelected]=useState<GalleryItem|null>(null); const [scrolled,setScrolled]=useState(false); const [installPrompt,setInstallPrompt]=useState<InstallPromptEvent|null>(null); const [guide,setGuide]=useState(false); const [shareDone,setShareDone]=useState(false); const [posts,setPosts]=useState(()=>[...instagramPosts].sort((a,b)=>(b.date||'').localeCompare(a.date||'')).slice(0,6));
 useEffect(()=>{const fn=()=>setScrolled(scrollY>30); const install=(e:Event)=>{e.preventDefault();setInstallPrompt(e as InstallPromptEvent)}; if(instagramDisplayMode==='random')setPosts([...instagramPosts].sort(()=>Math.random()-.5).slice(0,6)); addEventListener('scroll',fn); addEventListener('beforeinstallprompt',install); return()=>{removeEventListener('scroll',fn);removeEventListener('beforeinstallprompt',install)}},[]);
 const installHome=async()=>{if(installPrompt){await installPrompt.prompt();await installPrompt.userChoice;setInstallPrompt(null)}else setGuide(true)};
 const shareHome=async()=>{const data={title:'BOMI BEAUTY',text:'대구 복현동 네일·속눈썹·메이크업, 보미뷰티',url:location.href}; try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(location.href);setShareDone(true);setTimeout(()=>setShareDone(false),2200)}}catch{}}
 const visible=filter==='ALL'?gallery:gallery.filter(x=>x.category===filter);
 return <main>
  <header className={`site-header ${scrolled?'scrolled':''}`}><a className="wordmark" href="#home">BOMI BEAUTY</a><nav aria-label="주요 메뉴">{['HOME','ABOUT','SERVICE','STYLE','REVIEW','LOCATION'].map(x=><a key={x} href={`#${x.toLowerCase()}`}>{x}</a>)}</nav><a className="reserve-link" href={IG} target="_blank" rel="noreferrer">RESERVATION</a><button className="menu-button" onClick={()=>setMenu(!menu)} aria-label="메뉴 열기"><i/><i/></button></header>
  {menu&&<div className="mobile-menu">{['HOME','ABOUT','SERVICE','STYLE','REVIEW','LOCATION'].map(x=><a key={x} onClick={()=>setMenu(false)} href={`#${x.toLowerCase()}`}>{x}</a>)}</div>}
  <section className="hero" id="home"><div className="hero-copy"><p className="eyebrow">BEAUTY, JUST FOR YOU</p><h1>BOMI<br/>BEAUTY</h1><p className="hero-korean">오늘의 나를<br/>조금 더 예쁘게</p><p className="services-line">NAIL · EYELASH · MAKEUP</p><div className="hero-actions"><a className="button primary" href={IG} target="_blank" rel="noreferrer">Instagram</a><a className="button text-button" href={IG} target="_blank" rel="noreferrer">Reservation <span>↗</span></a></div><span className="hero-place">DAEGU · BOKHYEON</span></div><div className="hero-visual"><img src="https://images.unsplash.com/photo-1610992015732-2449b76344bc?auto=format&fit=crop&w=1600&q=88" alt="은은한 네일 스타일"/><div className="hero-stamp">B<small>omi beauty</small></div></div></section>
  <section className="about section" id="about"><div className="section-label">01 — ABOUT BOMI</div><div className="about-copy"><h2>{aboutContent.title.split('\n').map((x,i)=><span key={i}>{x}</span>)}</h2><p>{aboutContent.body.split('\n').map((x,i)=><span key={i}>{x}</span>)}</p><a className="arrow-link" href={IG} target="_blank" rel="noreferrer">OUR STORY <b>↗</b></a></div><div className="about-images"><div className="portrait"><img src="/interior-editorial.png" alt="보미뷰티의 밝고 차분한 실내 공간"/></div><figure className="exterior-photo"><img src="/storefront-editorial.png" alt="대구 복현동 보미뷰티 매장 외관"/><figcaption><span>OUR SPACE</span><strong>BOMI BEAUTY · BOKHYEON</strong></figcaption></figure></div></section>
  <section className="service section" id="service"><header className="section-heading"><div><span>02 — OUR SERVICE</span><h2>BEAUTY<br/>SERVICE</h2></div><p>당신다운 아름다움을 위한<br/>섬세한 서비스를 만나보세요.</p></header><div className="service-grid">{services.map((s,i)=><article className="service-item" key={s.id}><div className="service-image"><img src={s.image} alt={s.name}/><span>0{i+1}</span></div><h3>{s.name}</h3><p>{s.description}</p><a href={IG} target="_blank" rel="noreferrer">RESERVATION ↗</a></article>)}</div></section>
  <section className="style section" id="style"><header className="style-head"><div><span>03 — PORTFOLIO</span><h2>BOMI STYLE</h2></div><div className="filters">{['ALL','NAIL','LASH','MAKEUP'].map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div></header><div className="gallery">{visible.map((item,i)=><button className={`gallery-item g${i%4}`} onClick={()=>setSelected(item)} key={item.image}><img src={item.image} alt={item.title}/><span>{item.category}</span><div><b>{item.title}</b><small>VIEW</small></div></button>)}</div></section>
  <section className="moments section" id="moments"><div className="moment-intro"><span>04 — SOCIAL</span><h2>BOMI<br/>MOMENTS</h2><p>보미뷰티의 새로운 스타일과<br/>다양한 시술 순간을 랜덤으로 만나보세요.</p><a className="outline-button" href={IG} target="_blank" rel="noreferrer">FOLLOW @_semi_kang ↗</a></div>{posts.length?<div className="post-grid">{posts.map(p=><article className="instagram-embed" key={p.url}>{p.thumbnail?<a href={p.url} target="_blank" rel="noreferrer"><img src={p.thumbnail} alt="Instagram 콘텐츠"/></a>:<iframe src={instagramEmbed(p.url)} title={`Instagram ${p.type}`} loading="lazy" allowFullScreen/>}<a href={p.url} target="_blank" rel="noreferrer"><b>{p.type==='reel'?'REEL':'POST'}</b> Instagram에서 보기 ↗</a></article>)}</div>:<a className="instagram-empty" href={IG} target="_blank" rel="noreferrer"><div>Instagram</div><p>새로운 작업과 소식은<br/><b>@_semi_kang</b>에서 먼저 만나보세요</p><span>VIEW FEED ↗</span></a>}</section>
  <section className="talk"><div><span>THREADS · BOMI TALK</span><h2>사진으로 다 하지 못한 이야기<br/>조금 더 편하게 만나는 보미뷰티</h2></div><a href={THREADS} target="_blank" rel="noreferrer">FOLLOW ON THREADS ↗</a></section>
  <section className="review section" id="review"><header className="section-heading"><div><span>05 — REVIEW</span><h2>BOMI REVIEW</h2></div></header>{reviews.length?<div className="review-grid">{reviews.map((r,i)=><article key={i}><p>“{r.content}”</p><span>{r.author} · {r.service}</span></article>)}</div>:<div className="empty-review"><span>COMING SOON</span><p>고객 후기 준비 중입니다</p><small>보미뷰티에서의 소중한 경험을 곧 소개할게요.</small></div>}</section>
  <section className="location section" id="location"><div className="location-visual"><div className="map-mark">B<span>OMI BEAUTY</span></div><p>KYUNGJIN-RO 1-GIL</p></div><div className="location-copy"><span>06 — VISIT BOMI</span><h2>Come visit<br/>our studio.</h2><h3>대구광역시 북구 경진로1길 51-1</h3><p>대구 북구 복현동<br/>영진전문대학교 후문 인근</p><small>방문 전 예약 문의 부탁드립니다.</small><div className="location-actions"><a href={NAVER} target="_blank" rel="noreferrer">네이버 검색</a><a href={MAP} target="_blank" rel="noreferrer">카카오맵</a><a className="featured" href={IG} target="_blank" rel="noreferrer">예약 문의</a></div></div></section>
  <section className="home-tools"><div className="home-tool-mark">B</div><div><span>BOMI ON YOUR HOME</span><h2>홈 화면에서 바로 만나요</h2><p>앱처럼 추가하고, 공유 버튼으로 보미뷰티를 간편하게 전해보세요.</p></div><div className="home-tool-actions"><button onClick={installHome}>홈 화면에 추가</button><button onClick={shareHome}>홈페이지 공유</button></div></section>
  <footer><div className="footer-brand">BOMI BEAUTY</div><p>NAIL · EYELASH · MAKEUP</p><div><a href={IG} target="_blank" rel="noreferrer">Instagram</a><a href={THREADS} target="_blank" rel="noreferrer">Threads</a></div><small>© 2026 보미뷰티. 모든 권리 보유.</small><p className="copyright">본 웹사이트에 게시된 사진, 이미지, 영상, 글과 디자인 등 모든 콘텐츠의 권리는 보미뷰티에 있습니다.<br/>관련 법령이 허용하는 경우를 제외하고 사전 동의 없는 복제·배포·전송·게시·가공·상업적 이용 및 인공지능 학습·데이터 수집 목적의 이용을 금지합니다.</p></footer>
  <div className="mobile-cta"><a href={IG} target="_blank" rel="noreferrer">Instagram</a><a href={IG} target="_blank" rel="noreferrer">Reservation</a></div>
  {selected&&<div className="lightbox" role="dialog" onClick={()=>setSelected(null)}><button aria-label="닫기">×</button><img src={selected.image} alt={selected.title}/><div><span>{selected.category}</span><h3>{selected.title}</h3><p>{selected.description}</p></div></div>}
  {guide&&<div className="install-guide" role="dialog" onClick={()=>setGuide(false)}><div onClick={e=>e.stopPropagation()}><button onClick={()=>setGuide(false)} aria-label="닫기">×</button><span>홈 화면에 추가</span><h3>보미뷰티를 앱처럼 열어보세요</h3><p><b>iPhone · iPad</b><br/>Safari 하단의 공유 버튼을 누른 뒤<br/>‘홈 화면에 추가’를 선택해 주세요.</p><p><b>Android</b><br/>Chrome 오른쪽 위 메뉴에서<br/>‘앱 설치’ 또는 ‘홈 화면에 추가’를 선택해 주세요.</p></div></div>}
  {shareDone&&<div className="share-toast">홈페이지 주소를 복사했어요</div>}
 </main>
}
